import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { getLocale, getGT } from "gt-next/server";
import { GTProvider, LocaleSelector } from "gt-next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export async function generateMetadata(): Promise<Metadata> {
  const t = await getGT();
  return {
    title: t("Create Next App"),
    description: t("Generated by create next app")
  };
}

export default async function RootLayout({
  children


}: Readonly<{children: React.ReactNode;}>) {
  return (
  <html lang={await getLocale()}>
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased`}><GTProvider>
        <header className="w-full flex justify-end p-4">
          <LocaleSelector />
        </header>
        {children}
      </GTProvider></body>
    </html>
  );
}